### ISSUE TITLE
axios@0.19.2 have Critical security vulnerability

### ISSUE THREAD

**Issue by alchu4n** [momosecurity/mosec-node-plugin#1]
![image](https://user-images.githubusercontent.com/97670155/158328579-cf261ec1-8c87-4489-b6c0-abf255cce89a.png)

`
Need to install the following packages:
  github:momosecurity/mosec-node-plugin
Ok to proceed? (y) y
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
`

**Comment by retanoj** [comment]
Thank you for your mention
